- name: "Create conf and volume directories"
  file: path={{ item.path }} state=directory recurse=yes
  with_items:
    - { path: '/docker/caddy' }
    - { path: '/docker/caddy/vhosts' }
    - { path: '/docker/caddy/html' }

- name: "Create default Caddyfiles from templates"
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'Caddyfile.j2', dest: '/docker/caddy/Caddyfile' }
    - { src: 'vhost.j2', dest: '/docker/caddy/vhosts/server' }

- name: "Copy static website files"
  copy: src={{ item.path }} dest=/docker/caddy/html/{{ item.path }}
  with_items:
    - { path: 'index.html' }
    - { path: 'rc51.jpg' }

- name: "Copy docker-compose.yml"
  copy: src=docker-compose.yml dest=/docker/caddy/docker-compose.yml

- name: "Pull docker images"
  shell: '/usr/bin/docker pull {{ item.provider }}/{{ item.image }}:{{ item.tag }}'
  with_items: "{{ docker_images }}"

- name: "Create External Network"
  shell: '/usr/bin/docker network create external_network'

- name: "Start caddy container"
  shell: '/usr/local/bin/docker-compose up -d'
  args:
    chdir: /docker/caddy/
