version: "2"

services:
  caddy:
    container_name: caddy
    image: abiosoft/caddy:latest
    restart: always
    volumes:
      - /docker/caddy/Caddyfile:/etc/Caddyfile
      - /docker/caddy/vhosts:/etc/caddy/vhosts
      - /docker/caddy/html:/etc/caddy/html
      - /docker/caddy/home:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - external_network

networks:
  external_network:
    external: True
